# Generated by Django 4.0.1 on 2022-01-14 02:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=15, default=None, max_digits=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=15, default=None, max_digits=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(decimal_places=15, default=None, max_digits=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(decimal_places=15, default=None, max_digits=20),
        ),
    ]
