# Generated by Django 4.0.1 on 2022-01-17 00:26

import core.models.property
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_location_created_at_property_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='property',
            name='longitude',
        ),
        migrations.AddField(
            model_name='property',
            name='full_limits',
            field=models.JSONField(default=core.models.property.limits_info, verbose_name='limitsInfo'),
        ),
    ]
